default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      # - id: check-shebang-scripts-are-executable # support in lastest ref
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.6
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.0'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.31.0'
    hooks:
      - id: yapf
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.16.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/yoheimuta/protolint
    rev: v0.31.0
    hooks:
      - id: protolint
  # - repo: https://github.com/markdownlint/markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/rubocop/rubocop
    rev: v1.14.0
    hooks:
      - id: rubocop
  - repo: https://gist.github.com/curoky/cd141455853d28e61b61e54220a7eaa5
    rev: 'master'
    hooks:
      - id: shfmt
      - id: shellcheck
      - id: buildifier
      - id: clang-format
      # - id: cpplint
      - id: cppcheck
      - id: cmake-format
      - id: bean-format
      - id: isort
      - id: licenseheaders
        args: ['--years', '2019', '--files']
